---
title: "CSBC/PS-ON Knowledge Portal"
subtitle: "Resource & Activity Overview"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: lumen
    runtime: shiny
---

```{r setup, include=TRUE}
library(flexdashboard)
library(lubridate)
library(tidyverse)
library(plotly)
library(shiny)
library(crosstalk)
library(DT)
library(synapser)
library(streamgraph)
library(dplyr)
library(ggridges)
library(ggthemes)
library(kableExtra)

source("../R/synapse_helpers.R")
source("../R/tables.R")
source("../R/charts.R")
```

```{r, include=FALSE}
synLogin()
csbc_summary_df <- get_table_df("syn11958165", cache = TRUE)

csbc_summary_df <- csbc_summary_df %>% 
    mutate_at(.vars = vars(dplyr::matches("(createdOn|modifiedOn)")),
              .funs = funs(lubridate::as_datetime(floor(. / 1000))))
```

```{r}
project_vars <- c("projectId", "name_project", "institution", "consortium",
                  "grantNumber", "grantType", "teamMembersProfileId",
                  "teamProfileId", "createdOn_project", "modifiedOn_project",
                  "publication_count", "publication_geodata_produced")
count_vars <- c("fileId", "individualID", "specimenID", "cellLine",
                "assay", "tool")
center_study_summary_df <- csbc_summary_df %>% 
    mutate(tool = ifelse(!is.na(softwareLanguage), study, NA)) %>% 
    group_by(.dots = c(project_vars, "study")) %>% 
    summarise_at(.vars = count_vars,
                 .funs = funs(n_distinct(., na.rm = TRUE))) %>% 
    replace_na(list(study = "Not Annotated")) %>% 
    mutate(study = ifelse(fileId == 0, NA, study))
```


```{r}
center_summary_df <- center_study_summary_df %>% 
    group_by(projectId) %>% 
    summarise(study = n_distinct(study, na.rm = TRUE)) %>% 
    ungroup() %>% 
    left_join(
        center_study_summary_df %>% 
            select(-study) %>% 
            group_by(.dots = project_vars) %>% 
            summarise_all(sum),
        by = "projectId"
    )
```



Portal at a Glance
=====================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

---

**About**

Welcome to the CSBC/PS-ON Knowledge Portal Dashboard!

---


Row
-----------------------------------------------------------------------

### Centers

```{r}
centers <- n_distinct(center_study_summary_df$projectId)
valueBox(centers, icon = "fa-university")
```

### Files

```{r}
files <- sum(center_study_summary_df$fileId)
valueBox(files, icon = "fa-file")
```

### Samples

```{r}
samples <- sum(
    sum(center_study_summary_df$individualID),
    sum(center_study_summary_df$cellLine),
    sum(center_study_summary_df$specimenID)
)
valueBox(samples, icon = "fa-tag")
```


### Publications

```{r}
pubs <- csbc_summary_df %>% 
    group_by(projectId) %>% 
    summarise(value = unique(publication_count)) %>% 
    pull(value) %>%
    sum()

valueBox(pubs, icon = "fa-pencil")
```


Row
-----------------------------------------------------------------------

### Data Shared

```{r}
centers_w_files <- center_summary_df %>%
    group_by(projectId) %>%
    summarize(file_count = sum(fileId)) %>%
    filter(file_count > 0) %>% nrow()
gauge(centers_w_files, min = 0, max = centers)
```

> (out of all Centers)


### Files in Studies

```{r}
files_w_study <- center_study_summary_df %>% 
    filter(!is.na(study),
           study != "Not Annotated") %>% 
    .[["fileId"]] %>% 
    sum()
    
gauge(files_w_study, min = 0, max = files)
```

> (out of all files)

Row {data-height=600}
-----------------------------------------------------------------------

### Center Activity

```{r}
plot_df <- center_study_summary_df %>% 
    mutate(sample = individualID + specimenID + cellLine) %>% 
    group_by(name_project, consortium, grantType) %>% 
    summarise(avg_files = mean(fileId),
           study = n_distinct(study, na.rm = TRUE)) %>% 
    ungroup() %>% 
    arrange(study) %>% 
    mutate(name_project = fct_inorder(name_project),
           label = glue::glue(
               "<b>{value}:</b>\n{count} studies\n{avg} files per study",
               value = name_project,
               count = study,
               avg = avg_files
           )
    )

p <- plot_df %>% 
    ggplot(aes(x = name_project, y = study, text = label)) +
    geom_col(aes(fill = avg_files)) +
    geom_point(aes(colour = grantType), y = 0.1) +
    coord_flip() +
    scale_colour_colorblind() +
    guides(alpha = FALSE, fill = FALSE, colour = guide_legend(title = NULL)) +
    xlab("") +
    ylab("Studies in Synapse") +
    scale_y_continuous(expand = c(0, 0)) +
    facet_grid(consortium ~ ., 
               scales = "free_y", space = "free_y", drop = TRUE) +
    theme_bw() +
    theme(strip.text.x = element_text(face = "bold"),
          strip.text.y = element_text(face = "bold"),
          strip.background.y = element_blank(),
          legend.title = element_blank())

ggplotly(p, tooltip = "text") %>%
    layout(legend = list(orientation = 'h',
                         y = 1, x = 0, yanchor = "bottom"),
           margin = list(b = 55)) %>% 
    plotly::config(displayModeBar = F)
```


KP Over Time
=====================================


Sidebar {.sidebar}
-----------------------------------------------------------------------

---

**Options**

---

```{r}
selectInput("sg_facet", label = "Group files by:",
            choices = c("projectId", "assay"), selected = "projectId")
radioButtons("sg_cumulative", label = "Aggregation:",
             choiceNames = c("Month-by-month", "Cumulative"),
             choiceValues = c(FALSE, TRUE),
             selected = TRUE)
```


---

Row {.tabset data-height=650}
-----------------------------------------------------------------------

### Files Added 

```{r}
streamgraphOutput("files_per_month", height = "100%")
output$files_per_month <- renderStreamgraph({
    sg_facet_chr <- input$sg_facet
    sg_facet <- as.name(input$sg_facet)
    
    plot_df <- csbc_summary_df %>% 
        select(createdOn_file, rlang::UQ(sg_facet)) %>% 
        mutate(month = as.Date(cut(createdOn_file, breaks = "month"))) %>% 
        filter(!is.na(month)) %>% 
        group_by(month, rlang::UQ(sg_facet)) %>% 
        tally() %>% 
        ungroup() %>%
        complete(month, rlang::UQ(sg_facet)) %>% 
        replace_na(list(n = 0L)) 
    
    if (input$sg_cumulative) {
        plot_df <- plot_df %>% 
            group_by(rlang::UQ(sg_facet)) %>%
            mutate(n = cumsum(n)) %>% 
            ungroup()
    } 
    plot_df <- plot_df %>% 
        mutate(n = log10(n + 1)) %>% 
        rename(sg_facet = rlang::UQ(sg_facet))
    
    streamgraph(as.list(plot_df), sg_facet, "n", "month", offset = "zero", 
                    interpolate = "step") %>%
        sg_axis_x(1, "month", "%m-%Y") %>%
        sg_fill_brewer("PuOr")
})
```

```{r}
# projects_w_files <- center_summary_df %>%
#     group_by(projectId) %>%
#     summarize(file_count = sum(fileId)) %>%
#     filter(file_count > 0) %>%
#     pull(projectId)
# 
# plot.dat <- filter(csbc_summary_df, projectId %in% projects_w_files)
# plot.dat <- plot.dat[,c('fileId', 'projectId', 'createdOn_file', 'study')]
# plot.dat <- mutate(plot.dat, date = format(as.Date(createdOn_file), "%y-%m"))
# plot.dat$study[is.na(plot.dat$study)] <- 'Other files'
# 
# ggplot(plot.dat, aes(x = date , y = study)) +
#     geom_density_ridges(aes(fill = study), alpha = 0.5, scale = 4,  scale = 3, size = 0.3) +
#     scale_x_discrete(expand = waiver()) + theme(legend.position = "none", axis.text.x = element_text(angle = 55, hjust = 1))
```


Center Summaries
=====================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

---

**Center Activity**

Select a row in the table to view details about a Center.

---

```{r}
h4(textOutput("center_name"))
observeEvent(input$center_summary_rows_selected, {
    output$center_name <- renderText({
        center_row <- input$center_summary_rows_selected
        center_summary_df[[center_row, "name_project"]]
    })
})
```

```{r}
tableOutput("center_metadata")
observeEvent(input$center_summary_rows_selected, {
    output$center_metadata <- function() {
        center_row <- input$center_summary_rows_selected
        selected_center <- center_summary_df[[center_row, "projectId"]]
        center_data_df <- center_summary_df %>%
            filter(projectId == selected_center) %>%
            select(project_vars) %>%
            select(-dplyr::matches("(On_project)")) %>%
            mutate(`Synapse Project` = projectId,
                   `Synapse Team` = glue::glue("{team_id} ({team_size} members)",
                                               team_id = teamProfileId,
                                               team_size = str_split(
                                                   teamMembersProfileId,
                                                   ", ", simplify = TRUE
                                               ) %>%
                                                   length())) %>%
            create_synapse_links(list(`Synapse Project` = "projectId",
                                      `Synapse Team` = "teamProfileId")) %>%
            mutate(`Synapse Team` = str_replace(`Synapse Team`,
                                                "#!Synapse", "#!Team")) %>%
            select(-projectId, -name_project,
                   -teamProfileId, -teamMembersProfileId) %>%
            gather(field, val) %>%
            mutate(field = str_to_title(field),
                   field = case_when(
                       field == "Grantnumber" ~ "Grant Number",
                       field == "Granttype" ~ "Grant Type",
                       field == "Publication_count" ~ "Publications",
                       field == "Publication_geodata_produced" ~ "GEO Datasets",
                       TRUE ~ field
                   ),
                   field = str_c("<b>", field, "</b>")
            ) 
        
        knitr::kable(center_data_df, "html", escape = FALSE, col.names = NULL,
                     align = c('r', 'l')) %>% 
            kable_styling("striped", full_width = F)
    }
})

```

Row
-----------------------------------------------------------------------

### Center Snapshot

```{r}
DT::dataTableOutput("center_summary", width = "100%")

output$center_summary <- DT::renderDT({
    center_summary_df %>% 
        select(
            Center = name_project,
            Studies = study,
            Files = fileId,
            Assays = assay,
            Individuals = individualID,
            Specimens = specimenID,
            `Cell Lines` = cellLine,
            Tools = tool
        ) %>% 
        datatable(selection = list(
            mode = 'single'
        ),
        options = list(
            scrollX = TRUE
        ),
        rownames = FALSE
        ) %>%
        formatStyle(
            'Files',
            backgroundColor = styleEqual(0.0, 'lightpink')
        )
}, server = FALSE
)
```


Row {.tabset}
-----------------------------------------------------------------------

### Overall Center Contributions

```{r}
plotly::plotlyOutput("center_details")
observeEvent(input$center_summary_rows_selected, {
output$center_details <- plotly::renderPlotly({
    if (length(input$center_summary_rows_selected)) {
        center_row <- input$center_summary_rows_selected
        selected_center <- center_summary_df[[center_row, "projectId"]]
        center_df <- csbc_summary_df %>% 
            filter(projectId == selected_center)
        
        # plot_keys <- list(assay = "Assays", tumorType = "Tumor Types",
        #           diagnosis = "Diagnoses", species = "Species",
        #           organ = "Organs", tissue = "Tissues",
        #           dataType = "Data Types", study = "Studies")
        # 
        # chart <- center_df %>%
        #     plot_file_counts_by_annotationkey(plot_keys, chart_height = 300)
        # chart
        
        p <- center_df %>%
            mutate(tool = ifelse(!is.na(softwareLanguage), study, NA)) %>%
            select(
                Studies = study,
                `Tumor Types` = tumorType,
                Species = species,
                Assays = assay,
                Tools = tool
            ) %>%
            gather(attr, val) %>%
            group_by(attr, val) %>%
            tally() %>%
            replace_na(list(val = "Not Annotated")) %>%
            group_by(attr) %>%
            mutate(files = sum(n)) %>%
            ungroup() %>%
            dplyr::mutate(label = glue::glue(
                "<b>{value}:</b>\n{count} of {total} files",
                value = val,
                count = n,
                total = files)
            ) %>%
            ggplot(aes(x = 1, y = n, text = label)) +
            geom_col(aes(fill = val), 
                     position = position_stack(reverse = FALSE)) +
            guides(fill = FALSE) +
            scale_fill_viridis_d() +
            scale_y_continuous(expand = c(0, 0)) +
            xlab("") +
            ylab("Fraction") +
            facet_grid(. ~ attr, scales = "free_y") +
            theme(axis.text.x = element_blank(),
                  axis.ticks.x = element_blank()) %>%
            I
        ggplotly(p, tooltip = "text") %>%
            layout(showlegend = FALSE) %>%
            plotly::config(displayModeBar = F)
    }
})
})
```

### Contributions by Study

```{r}
# plotly::plotlyOutput("center_study_details")
# output$center_study_details <- plotly::renderPlotly({
#     center_row <- input$center_summary_rows_selected
#     selected_center <- center_summary_df[[center_row, "projectId"]]
#     center_df <- center_summary_df %>% 
#         filter(projectId == selected_center)
# 
#     p <- center_df %>%
#         select(projectId) %>%
#         left_join(center_study_summary_df, by = "projectId") %>%
#         select(-one_of(project_vars)) %>%
#         gather(attr, count, -study) %>%
#         ggplot(aes(x = 1, y = count)) +
#         geom_col() +
#         xlab("") +
#         facet_grid(study ~ attr, scales = "free_y") +
#         theme(axis.text.x = element_blank(),
#               axis.ticks.x = element_blank(),
#               strip.background.y = element_blank(),
#               strip.text.y = element_text(angle = 0, hjust = 0))
#     ggplotly(p)
# })
```






