---
title: "Data-specific Updates"
output: 
  html_notebook:
    code_folding: "hide"
---

```{r, message=FALSE, echo=FALSE}
library(synapseClient,quietly=TRUE)
library(tidyverse,quietly=TRUE)
library(ggplot2,quietly=TRUE)
library(forcats,quietly=TRUE)
library(viridis,quietly=TRUE)
library(plotly,quietly=TRUE)
```

This document refers to the pan-CSBC file view (`syn9630847`), but can be applied to any file view.
```{r, message=FALSE, include=FALSE}
synapseLogin()
fv_table <- synTableQuery("select * from syn9630847")
fv_df <- fv_table@values
```

```{r,message=FALSE}
proj_info<-sapply(unique(c(fv_df$projectId)),function(x) {
  res=synGet(x)
  c(projectId=x,Center=res@properties$name,Program=res@annotations$consortium,Institution=res@annotations$institution)})

proj_info=data.frame(t(proj_info))
```

###Data annotation summaries

####Available Assays
```{r}
assay_counts=fv_df%>%group_by(assay)%>%summarize(Centers=n_distinct(projectId),Files=n_distinct(id),tumorType=n_distinct(tumorType),disease=n_distinct(diagnosis),specimens=n_distinct(specimenID),patients=n_distinct(individualID))

arrange(assay_counts,desc(Centers))
```

```{r}
assay_stats=fv_df%>%group_by(assay,tumorType,diagnosis)%>%summarize(Centers=n_distinct(projectId),Files=n_distinct(id),specimens=n_distinct(specimenID),patients=n_distinct(individualID))

arrange(assay_stats,desc(Centers))
```

```{r}
p=ggplot(assay_stats)+geom_bar(aes(x=assay,fill=tumorType,y=Files),stat='identity',position='dodge')+ggtitle('Files by assay,tumor type')+scale_fill_viridis(discrete = TRUE) + xlab("") +scale_y_log10()+ coord_flip()+
    ylab("") +
    theme(plot.title = element_text(face = "bold"),
          legend.title = element_blank(), axis.text.x = element_text(angle = 315, hjust = 1))

ggplotly(p, width = 1000) %>%
    layout(margin = list(l = 100, r = 100,b=55))
```

```{r}


p=ggplot(assay_stats)+geom_bar(aes(x=assay,fill=diagnosis,y=Files),stat='identity',position='dodge')+ggtitle('Files by assay,diagnosis')+scale_fill_viridis(discrete = TRUE) + xlab("") + scale_y_log10()+
    ylab("") +coord_flip()+
    theme(plot.title = element_text(face = "bold"),
          legend.title = element_blank(), axis.text.x = element_text(angle = 315, hjust = 1))

ggplotly(p, width = 1000) %>%
    layout(margin = list(l = 100, r = 100,b=55))
```

```{r}
disease_counts=fv_df%>%group_by(diagnosis)%>%summarize(Centers=n_distinct(projectId),Files=n_distinct(id),tumorType=n_distinct(tumorType),assay=n_distinct(assay),specimens=n_distinct(specimenID),patients=n_distinct(individualID))

arrange(disease_counts,desc(Centers))
```


```{r}
tt_counts=fv_df%>%group_by(tumorType)%>%summarize(Centers=n_distinct(projectId),Files=n_distinct(id),disease=n_distinct(diagnosis),assay=n_distinct(assay),specimens=n_distinct(specimenID),patients=n_distinct(individualID))

arrange(tt_counts,desc(Centers))
```




```{r,message=FALSE}
synStore(File('dataTypeReporting.Rmd',parentId='syn10518272'))

synStore(File('dataTypeReporting.nb.html',parentId='syn10518272'))
```
