---
title: "Program Updates"
output: 
  html_notebook:
    code_folding: "hide"
---

```{r, message=FALSE, echo=FALSE}
library(synapseClient,quietly=TRUE)
library(tidyverse,quietly=TRUE)
library(ggplot2,quietly=TRUE)
library(forcats,quietly=TRUE)
library(viridis,quietly=TRUE)
library(plotly,quietly=TRUE)
```

*Currently this queries file views, need to fix to store in its own table*
```{r, message=FALSE, include=FALSE}
synapseLogin()
fv_table <- synTableQuery("select * from syn9630847")
fv_df <- fv_table@values

tv_table <- synTableQuery("select * from syn9898965")
tv_df <-tv_table@values
```

Below are the active projects within the CSBC and PS-ON:
```{r,message=FALSE}
proj_info<-sapply(unique(c(fv_df$projectId,tv_df$projectId)),function(x) {
  res=synGet(x)
  c(projectId=x,Center=res@properties$name,Program=res@annotations$consortium,Institution=res@annotations$institution)})

proj_info=data.frame(t(proj_info))
```

###Summary Tables

####Data Resources
```{r,message=FALSE}
file_counts=fv_df%>%group_by(projectId)%>%summarize(Files=n_distinct(id),Assays=n_distinct(assay),tumorType=n_distinct(tumorType),disease=n_distinct(diagnosis),specimens=n_distinct(specimenID),patients=n_distinct(individualID))

files_with_info=inner_join(proj_info,file_counts,by="projectId")

files_with_info
```

####Tool Resources
```{r,message=FALSE}
tool_counts=tv_df%>%group_by(projectId)%>%summarize(Files=n_distinct(id),ToolType=n_distinct(softwareType),ToolLanguage=n_distinct(softwareLanguage))

tools_with_info=inner_join(proj_info,tool_counts,by="projectId")

tools_with_info
```


###Data Summary Figures
```{r}

files_with_info=mutate(files_with_info,Label=paste(Institution,Program,sep='\n'))
files_with_info$text=paste('Institution:',files_with_info$Institution,'\nFiles:',files_with_info$Files)

p=ggplot(files_with_info,aes(text=text))+geom_bar(aes(x=Label,y=Files,fill=Center),stat='identity')+scale_y_log10()+ggtitle('Files uploaded by Center')+scale_fill_viridis(discrete = TRUE) + xlab("") +
    ylab("") + coord_flip()+
    theme(plot.title = element_text(face = "bold"),
          legend.title = element_blank(),
      axis.text.x = element_text(angle = 315, hjust = 1))

ggplotly(p, tooltip='text',width=1400) %>%
    layout(margin = list(l = 280, r = 85,b=55))
```

```{r}
files_with_info$text=paste('Institution:',files_with_info$Institution,'\nDiseases:',files_with_info$disease)

p=ggplot(files_with_info,aes(text=text))+geom_bar(aes(x=Label,y=disease,fill=Center),stat='identity')+ggtitle('Diseases studied by Center')+scale_fill_viridis(discrete = TRUE) + xlab("") +
    ylab("") + coord_flip()+
    theme(plot.title = element_text(face = "bold"),
          legend.title = element_blank(), legend.position='botom',
      axis.text.x = element_text(angle = 315, hjust = 1))

ggplotly(p,tooltip='text', width = 1400) %>%
   layout(margin = list(l = 280, r = 85,b=50))

```

```{r}
files_with_info$text=paste('Institution:',files_with_info$Institution,'\nPatients:',files_with_info$patients)

p=ggplot(files_with_info,aes(text=text))+geom_bar(aes(x=Label,y=patients,fill=Center),stat='identity')+ggtitle('Individual patients studied by Center')+scale_fill_viridis(discrete = TRUE)+  xlab("") +
    ylab("") + coord_flip()+
    theme(plot.title = element_text(face = "bold"),
          legend.title = element_blank(),
      axis.text.x = element_text(angle = 315, hjust = 1))

ggplotly(p,tooltip='text', width = 1400) %>%
    layout(margin = list(l = 285, r = 65,b=40))

```

```{r}
files_with_info$text=paste('Institution:',files_with_info$Institution,'\nAssays:',files_with_info$Assays)

p=ggplot(files_with_info,aes(text=text))+geom_bar(aes(x=Label,y=Assays,fill=Center),stat='identity')+ggtitle('Individual assays collected by Center')+scale_fill_viridis(discrete = TRUE)+  xlab("") +
    ylab("") + coord_flip()+
    theme(plot.title = element_text(face = "bold"),
          legend.title = element_blank(),
      axis.text.x = element_text(angle = 315, hjust = 1))

ggplotly(p, tooltip='text',width = 1300) %>%
    layout(margin = list(l = 280, r = 65,b=30))

```

```{r,message=FALSE}
synStore(File('fileViewReporting.Rmd',parentId='syn10518272'))

synStore(File('fileViewReporting.nb.html',parentId='syn10518272'))
```


