---
title: 
output: 
  flexdashboard::flex_dashboard:
    #orientation: columns
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
source("R/charts.R")
source("R/tables.R")
source("R/synapse_helpers.R")

# Script/template to create summary tables and charts for a "study"
synapseLogin()
# Config ------------------------------------------------------------------

synproject_id <- "syn5610418" # Synapse project for project Center
source_id <- "syn5610418" # Synapse folder associated with project
parent_id <- "syn10902919" # Center 'Reporting' folder where files should be stored
master_fileview_id <- "syn10903667" # Synapse fileview associated with project

# Collect data ------------------------------------------------------------

fileview_df <- get_table_df(master_fileview_id)
```
By Assay
=======================================================================

```{r}

summarize_datafiles_by_assay <- function(view_df, table_id) {
    count_cols <- c("id")
    view_df %>%
        group_by(assay) %>%
        summarise_at(count_cols, n_distinct) %>%
        rowwise() %>%
        mutate(sourceFileview = table_id,
               query = build_tablequery(sourceFileview, assay)) %>%
        add_queryview_column(format = "html") %>%
        select(-query)
}

datafile_counts_by_assay <- fileview_df %>%
    summarize_datafiles_by_assay(master_fileview_id)

knitr::kable(datafile_counts_by_assay)
```

By Species
=======================================================================

```{r}
summarize_datafiles_by_species <- function(view_df, table_id) {
    count_cols <- c("id")
    view_df %>%
        group_by(species) %>%
        summarise_at(count_cols, n_distinct) %>%
        rowwise() %>%
        mutate(sourceFileview = table_id,
               query = build_tablequery(sourceFileview, species)) %>%
        add_queryview_column(format = "html") %>%
        select(-query)
}

datafile_counts_by_species <- fileview_df %>%
    summarize_datafiles_by_species(master_fileview_id)

knitr::kable(datafile_counts_by_species)

```
By Data Type
=======================================================================

```{r}
summarize_datafiles_by_dataType <- function(view_df, table_id) {
    count_cols <- c("id")
    view_df %>%
        group_by(dataType) %>%
        summarise_at(count_cols, n_distinct) %>%
        rowwise() %>%
        mutate(sourceFileview = table_id,
               query = build_tablequery(sourceFileview, dataType)) %>%
        add_queryview_column(format = "html") %>%
        select(-query)
}

datafile_counts_by_dataType <- fileview_df %>%
    summarize_datafiles_by_dataType(master_fileview_id)

knitr::kable(datafile_counts_by_dataType)
```
