---
title: "R Notebook"
output: html_notebook
---


```{r}
list(assay = "Assay", tumorType = "Tumor Type") %>% 
    map2(.y = names(.), function(annotation_prettykey, annotation_key) {
        p <- fileview_df %>% 
            group_by(.dots = annotation_key) %>% 
            tally() %>% 
            ggplot(aes(x = 1, y = n)) +
            geom_col(aes_string(fill = annotation_key), 
                     colour = "white") +
            scale_fill_viridis_d() +
            xlab(annotation_prettykey) +
            ylab("") +
            theme_minimal() +
            theme(axis.text.x = element_blank(),
                  axis.ticks.x = element_blank()) +
            guides(fill = FALSE)
        ggplotly(p, tooltip = c("y", "fill"))
    }) %>% 
    subplot(shareY = TRUE, titleX = TRUE) %>% 
    layout(title = "File Annotation Summary",
           showlegend = FALSE,
           font = list(family = "Roboto"))

```

```{r, message=FALSE, warning=FALSE}
p <- list(tumorType = "Tumor Type", projectName = "Study") %>% 
    map2(.y = names(.), function(annotation_prettykey, annotation_key) {
        fileview_df %>%
            group_by(.dots = c("assay", annotation_key)) %>% 
            summarize(num_individuals = n_distinct(individualID)) %>% 
            ungroup() %>% 
            rename_(.dots = list(temp = annotation_key)) %>% 
            complete(temp = c(unique(temp), "NA"), assay) %>% 
            replace_na(list(num_individuals = 0)) %>% 
            rename_(.dots = setNames("temp", annotation_key)) %>%  
            gather(category, value, -assay, -num_individuals)
    }) %>% 
    bind_rows() %>% 
    ggplot(aes(x = value, y = assay)) +
    geom_tile(aes(fill = num_individuals)) +
    scale_fill_viridis_c("Num. Individuals") +
    scale_x_discrete(expand = c(0, 0)) +
    scale_y_discrete(expand = c(0, 0)) +
    xlab("") +
    ylab("") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "bottom",
          strip.text.x = element_text(face = "bold"),
          strip.background = element_blank()) +
    facet_grid(. ~ category, space = "free", scales = "free", switch = "y")
ggplotly(p, tooltip = c("x", "y", "fill")) %>%
    layout(title = "Individuals by Assay",
           font = list(family = "Roboto")) %>%
    style(xgap = 5, ygap = 5)
```


```{r}
# https://github.com/pinin4fjords/upset-shiny-plotly/blob/master/app.R
sets_df <- fileview_df %>% 
    filter(!(individualID == "H1" & assay == "rnaSeq")) %>% 
    group_by(individualID, assay) %>% 
    tally() %>%
    ungroup() %>% 
    right_join(., expand(., individualID, assay), 
               by = c("individualID", "assay")) %>%
    mutate(n = ifelse(is.na(n), 0L, 1L)) %>% 
    spread(assay, n) %>% 
    as.data.frame()
upset(sets_df, sets = unique(fileview_df$assay), order.by = "freq")
```



